baseURL = 'https://megan-tian.github.io/'
languageCode = 'en-us'
title = 'Megan Tian'
theme = 'shibui'

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[params]
  author = "Megan Tian"
  email = "megant@mit.edu"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Fun"
    url = "/fun/"
    weight = 3